name: Run Task Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1

      - name: Detect changed zadanie files
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '^tasks/zadanie_.*\.php$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run tests for changed files
        if: env.CHANGED_FILES != ''
        run: |
          for file in $CHANGED_FILES; do
            number=$(echo "$file" | grep -oP '(?<=zadanie_)\d+(?=\.php)')
            echo "Running tests for zadanie_$number.php..."
            php tests.php "$number"
          done
